services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: krisha-backend
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: krisha-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
